{% set name = "TIES_MD" %}
{% set version = "1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/UCL-CCS/TIES_MD/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 04f7a439793354a84c7538cc948ad40a7fffae9585a1f1d39ede9205bbbcf2b7

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  noarch: python
  entry_points:
    - ties_md = TIES_MD.cli:main
    - ties_ana = TIES_MD.ties_analysis.ties_analysis:main

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - docopt
    - multiprocess
    - numpy
    - openmm
    - pymbar =4.0.1
    - scipy
    - openmmtools
    - scikit-learn
    - scipy
    - six
    - matplotlib-base
    - seaborn

test:
  imports:
    - TIES_MD
  requires:
    - pip
    - pytest
  commands:
    - pip check
    - python -c "import pytest; pytest.main(['./TIES_MD-{{ version }}/TIES_MD/tests'])"

about:
  home: https://github.com/UCL-CCS/TIES_MD
  summary: 'Python package built on NAMD/OpenMM and OpenMMTools to perform binding free energy calculations
   using the TIES protocol. '
  description: |
    TIES_MD allows for the automation of binding free energy calculations in NAMD and OpenMM following the
    TIES protocol.
  license: LGPL-3.0-only
  license_file: COPYING
  doc_url: https://ucl-ccs.github.io/TIES_MD/
  dev_url: https://github.com/UCL-CCS/TIES_MD

extra:
  recipe-maintainers:
    - adw62
